#!/bin/bash

script_dir=`dirname "$0"`
if [ "${script_dir:0:1}" != "/" ]; then
    script_dir=`dirname $(pwd)/$script_dir`
fi

test_dir="${script_dir}/tests"

for f in "${test_dir}/*.expect"; do
  $f;
done;

